apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: echo-listener
spec:
  triggers:
    - name: simple-echo
      bindings:
        - ref: echo-pipeline-binding
      template:
        ref: echo-pipeline-template
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: echo-pipeline-binding
spec:
  params:
  - name: quote
    value: "Live and let die"
  - name: noquote
    value: "Enjoy the silence"
  - name: timestamp
    value: $(event.head_commit.timestamp)
  - name: event.commits
    value: $(event.commits)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: echo-pipeline-template
spec:
  params:
    - name: quote
      description: Quoted property
      default: "My kingdom for a quote"
    - name: noquote
      description: UnQuoted property
      default: "Who needs a quote anyway"
    - name: timestamp
      description: Timestamp of first commit
      default: "1970-01-01T00:00:00Z"
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: echo-pipeline-run-
      spec:
        pipelineRef:
          name: echo-props-pipeline
        params:
          - name: quote
            value: $(tt.params.quote)
          - name: noquote
            value: $(tt.params.noquote)
          - name: timestamp
            value: $(params.timestamp)  
