apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: echo-props-pipeline
spec:
  workspaces:
  - name: pipeline-pvc  
  params:
    - name: quote
      description: simple quoted property
      default: TESTQUOTE
    - name: noquote
      description: simple unquoted property
      default: TESTNOQUOTE
    - name: environment_value
      description: A value from the pipeline level, trigger level or run level
      default: BLOOPER 
    - name: timestamp
      description: Git commit timestamp
      default: EMPTYTIMESTMAP   
  tasks:
    - name: show-build-number
      workspaces:
      - name: shareddata
        workspace: pipeline-pvc
      taskRef:
        name: simple-task
    - name: echo-task
      taskRef:
        name: echo-props
      params:
        - name: quote
          value: $(params.quote)
        - name: noquote
          value: $(params.noquote)
        - name: environment_value
          value: $(params.environment_value)
        - name: timestamp
          value: $(params.timestamp)  
    - name: cm-echo-task
      taskRef:
        name: cm-echo-props
    - name: env-echo-task
      taskRef: 
        name: cm-all-props
    - name: cm-secrets-all-props
      taskRef:
        name: cm-secrets-props
    - name: cm-toolchain-props
      taskRef:
        name: cm-toolchain-props
    - name: show-cm-event-parameters
      taskRef:
        name: cm-event-parameters    
